site_name: "mobile-developer-guide"
site_description: "A guide to mobile application development for the Government of the Province of British Columbia"
repo_url: https://github.com/bcgov/mobile-developer-guide
edit_uri: edit/main/docs/

nav:
  - Introduction: index.md
  - Project initiation: getting_started.md
  - Distribution methods: distribution_methods.md
  - Managing your app: app_management.md
  - Mobile app development guide: developer.md
  - Apple app signing: apple_app_signing.md
  - Google app signing: google_app_signing.md
  - Google signing for React Native apps: google_react_native_signing.md
  - Publish your app: publish.md
  - Encryption export regulations: encryption.md
  - Community meetups: meetups.md
  - Contact us: contact.md
plugins:
  - techdocs-core
  - git-revision-date-localized
  - redirects:
    redirect_maps:
      'test.md': 'https://dev.developer.gov.bc.ca/docs/default/component/bc-developer-guide/security/security-and-privacy-compliance-and-guidance/'